# Generated by Django 3.1.4 on 2021-03-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_auto_20210227_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='image',
            new_name='images',
        ),
    ]
