# Generated by Django 3.1.4 on 2021-03-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_auto_20210301_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='images',
        ),
        migrations.AddField(
            model_name='photos',
            name='outfit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wardrobe.outfit'),
        ),
    ]
