# Generated by Django 3.1.4 on 2021-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_auto_20210312_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
