# Generated by Django 3.1.4 on 2021-03-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_auto_20210312_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
