# Generated by Django 3.1.4 on 2021-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0011_occasion_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='style',
            field=models.ManyToManyField(related_name='style', to='wardrobe.Style'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='styles',
            field=models.ManyToManyField(related_name='styles', to='wardrobe.Style'),
        ),
    ]
