# Generated by Django 3.1.4 on 2021-05-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0013_auto_20210505_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occasion',
            new_name='Occassion',
        ),
    ]
