# Generated by Django 3.1.4 on 2021-05-30 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfit', to=settings.AUTH_USER_MODEL),
        ),
    ]
