# Generated by Django 3.1.4 on 2021-11-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0018_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occassion',
            name='styles',
        ),
    ]
