# Generated by Django 3.1.4 on 2021-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0019_remove_occassion_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='occassion',
            name='styles',
            field=models.ManyToManyField(related_name='styles', to='wardrobe.Style'),
        ),
    ]
