# Generated by Django 3.1.4 on 2021-12-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0023_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AddField(
            model_name='gender',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='wardrobe.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='wardrobe.gender'),
        ),
    ]
