# Generated by Django 3.1.4 on 2022-01-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0025_inspiration_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
