# Generated by Django 3.1.4 on 2022-02-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0026_auto_20220131_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inspiration',
            field=models.ManyToManyField(related_name='Inspiration', to='wardrobe.Inspiration'),
        ),
    ]
